dependencies:
  - python=3.7
  - cudatoolkit=10.1
  - pytorch::pytorch=1.6
  - pytorch::torchvision
  - open3d-admin::open3d
  - anaconda
  - cudnn
  - pip
  - pip:
    - pip
    - detectron2
    - -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu101/torch1.6/index.html
    - pytorch-lightning<1.2.0
    - av
    - opencv-python
    - pillow-simd
    - avi-r
    - py-turbo
    - moviepy
    - decord
    - test_tube
    - retrying
    - pycocotools
    - webcolors
    - munkres
    - dill
    - lap
    - cython_bbox
    - einops
    - optuna
    - git+https://github.com/facebookresearch/SlowFast.git
    - addict
    - plyfile
