name: actev
channels:
  - pytorch
  - open3d-admin
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pytorch=1.6
  - cudatoolkit=10.1
  - pip
  - opencv
  - open3d
  - torchvision
  - pytorch-lightning
  - optuna
  - anaconda
  - pip:
    - pip
    - -r requirements.txt
