name: actev
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.5
  - cudatoolkit=10.2
  - pip
  - opencv
  - torchvision
  - anaconda
  - pip:
    - pip
    - avi-r
    - py-turbo
    - moviepy
    - pycocotools
    - detectron2
    - -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu102/torch1.5/index.html
