name: actev
channels:
  - pytorch
  - open3d-admin
  - defaults
dependencies:
  - python=3.7
  - pytorch=1.5
  - cudatoolkit=10.1
  - pip
  - opencv
  - open3d
  - torchvision
  - anaconda
  - pip:
    - pip
    - -r requirements.txt
